### ISSUE TITLE
Bug in Emscripten 1.32.4

### ISSUE THREAD

**Issue by thegodone** [cheminfo/RDKitjs#14]
We cannot use this version to bind RDKit for the moment.

**Comment by targos** [comment]
I think we need to include the dependencies in the project, so that we can choose the version and have them compile using the Makefile

**Comment by zeld** [comment]
I can write a cmake modules to find specific version of em++ and other dependencies.

**Comment by thegodone** [comment]
We can work with the last version 1.34.2
