### ISSUE TITLE
Descriptors._descList

### ISSUE THREAD

**Issue by thegodone** [cheminfo/RDKitjs#7]
how to do this python command ?

**Comment by thegodone** [comment]
here the python definition
 _descList=[] 
 20 -def _setupDescriptors(namespace): 
 21    global _descList,descList 
 22    from rdkit.Chem import GraphDescriptors,MolSurf,Lipinski,Fragments,Crippen 
 23    from rdkit.Chem.EState import EState_VSA 
 24    mods = [GraphDescriptors,MolSurf,EState_VSA,Lipinski,Crippen,Fragments] 
 25   
 26    otherMods = [Chem] 
 27   
 28    for nm,thing in namespace.items(): 
 29      if nm[0]!='_' and _isCallable(thing): 
 30        _descList.append((nm,thing)) 
 31     
 32    others = [] 
 33    for mod in otherMods: 
 34      tmp = dir(mod) 
 35      for name in tmp: 
 36        if name[0] != '_': 
 37          thing = getattr(mod,name) 
 38          if _isCallable(thing): 
 39            others.append(name) 
 40   
 41    for mod in mods: 
 42      tmp = dir(mod) 
 43   
 44      for name in tmp: 
 45        if name[0] != '_' and name[-1] != '_' and name not in others: 
 46          # filter out python reference implementations: 
 47          if name[:2]=='py' and name[2:] in tmp: 
 48            continue 
 49          thing = getattr(mod,name) 
 50          if _isCallable(thing): 
 51            namespace[name]=thing 
 52            _descList.append((name,thing)) 
 53    descList=_descList 
 54

**Comment by thegodone** [comment]
we want to reproduce this 
import sys
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

file_in  = sys.argv[1]
file_out = file_in+".descr.sdf"
ms = [x for x in  Chem.SDMolSupplier(file_in) if x is not None]
ms_wr = Chem.SDWriter(file_out)

nms=[x[0] for x in Descriptors._descList]
#nms.remove('MolecularFormula')
calc = MoleculeDescriptors.MolecularDescriptorCalculator(nms)

for i in range(len(ms)):
  descrs = calc.CalcDescriptors(ms[i])
  for x in range(len(descrs)):
    ms[i].SetProp(str(nms[x]),str(descrs[x]))
  ms_wr.write(ms[i])

**Comment by zeld** [comment]
I'm working on this section.

**Comment by thegodone** [comment]
Cool

Envoyé de mon iPhone

**Comment by thegodone** [comment]
Bonjour thegodone/RDKitjs,
guillaume godin vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/2vBDJ3/9rq/?hg=QXPcWmK0Zz pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e02e707d&email=reply@reply.github.com.&hg=QXPcWmK0Zz
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by thegodone** [comment]
Bonjour,

Guillaume  vient de s'inscrire sur IQ Elite. Il vous a écrit un message. 

Pour lire ce message avant qu'il n'expire, il suffit de cliquer sur le lien suivant : a.iqelite.com/entry/new_message/2d435e1f6f6aa35fdc444d40bbee203c2d3fda9e1f544b80bfb/320c612f7502e5151585f59af7b60bd585f826d67bd5f906d826d82519090827b59a9cca883bd5f83bd826ecb747b8259c4586eaf6d829060b7cb515151515151515858588275b0cb67cb9060a8587b91b7c4516d91a875b0a9bdc320c612f75044d3e22edb35af44b80bfb/?hg=1yMC5zoxYa

Lisez votre message avant qu'il ne disparaisse !            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e02e707d&email=reply@reply.github.com.&hg=1yMC5zoxYa
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by thegodone** [comment]
Bonjour,

Votre ami Guillaume vous a envoyé un message il y a 36h jours, mais vous ne l'avez toujours pas lu. 

Le message sera supprimé dans 24 heures. 

Pour savoir ce que Guillaume vous a écrit, cliquez ici : a.iqelite.com/entry/new_message/2d435e1f6f6aa35fdc444d40bbee203c2d3fda9e1f544b80bfb/320c612f7502e5151585f59af7b60bd585f826d67bd5f906d826d82519090827b59a9cca883bd5f83bd826ecb747b8259c4586eaf6d829060b7cb515151515151515858588275b0cb67cb9060a8587b91b7c4516d91a875b0a9bdc320c612f75044d3e22edb35af44b80bfb/?hg=tOlin8wv7P            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e02e707d&email=reply@reply.github.com.&hg=tOlin8wv7P
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
